### ISSUE TITLE
Dying mobs

### ISSUE THREAD

**Issue by Masceus** [vawser/Cinders-DS3#2]
I downloaded the most recent version and random mobs occasionally died. This happened in the trial of perseverance (random souls were gained without killing mobs) and more specifically, Pyromancer Dunnel instantly died upon spawning in. Mobs also seemed to die sometimes on warping into zones. This wasn't happening in 1.65 though.

**Comment by luciusmagn** [comment]
I haven't experienced this with Dunnel, but otherwise, can confirm

**Comment by loicprodhom** [comment]
Friend and I had this happen to Aldritch as we ran past Sulyvahn's boss room, it happened again for the Twin Princes, but we managed to avoid it by exiting the game as we heard the death sound
