### ISSUE TITLE
Effects on helms only

### ISSUE THREAD

**Issue by IamFireblizz** [vawser/Cinders-DS3#26]
I have no idea where to post this but having the choice to use different pieces of armors was really better than relyng only on head gear as is somethiing dark souls III always missed, having areason to use seomething beside appereance and resistances.
Having those gauntlets having different and unique effects aswell, no idea why you choose to change and make all Armors Pieces a trivial manner again.

**Comment by N0repi** [comment]
I agree. I much prefered the prior system.
