### ISSUE TITLE
Blood Loss Affects Illusory Insignia

### ISSUE THREAD

**Issue by dannielkars** [vawser/Cinders-DS3#31]
It seems when your character is affected by blood loss, your illusory insignia reverts back to your regular head (it doesn't seem the body/emblem is affected). You can find the example images linked accordingly;

1. '[Cinders 1.90 Blood Loss Bug.jpg](https://files.catbox.moe/j9mzex.jpg)' (equipped helmet is Snail Shell)
2. '[Cinders 1.90 Blood Loss Bug (after moss clump).jpg](https://files.catbox.moe/qoot8n.jpg)' (insignia is Ringed Knight Hood)

The problem doesn't seem to be isolated to those items specifically, since I tested with other insignia and emblems, and only the insignia seem affected by blood loss. To be clear, the problem begins both when introduced to blood loss (when you're first attacked) and when blood loss actually occurs. 

![Cinders 1 90 Blood Loss Bug](https://user-images.githubusercontent.com/29988799/100962324-f3a21c80-34d8-11eb-9f1a-d16d19ee8744.jpg)
![Cinders 1 90 Blood Loss Bug (after moss clump)](https://user-images.githubusercontent.com/29988799/100962317-f270ef80-34d8-11eb-902e-289a8d215f45.jpg)

**Comment by dannielkars** [comment]
Addendum: To be more specific, it seems the insignia interference is more so a consequence of the maggots left by Corpse-Grub attacks, as mentioned [here](https://darksouls3.wiki.fextralife.com/Maggot-grub):

> Attacks that hit the player leave them with maggots. Maggots gradually build up Bleed and can be removed by Bonfires, Torches, Bloodred Moss Clumps or letting them apply bleed twice.

It seems the illusory insignia has not taken into account external effects like the maggots. Taking a moss clump gets rid of both the bleed _and_ the maggots, which reactivates the insignia. 

![Cinders 1 90 Blood Loss Bug (Corpse-Grub)](https://user-images.githubusercontent.com/29988799/100978121-cbc1b180-34f6-11eb-85cd-f5bb356e8f86.jpg)

**Comment by luciusmagn** [comment]
Hi, unfortunately, I can't help you, but may I ask how you get that cool UI with the items at the top like you got?

**Comment by dannielkars** [comment]
I added the corresponding '[Minimalistic HUD](https://www.nexusmods.com/darksouls3/mods/585)' folder to the Cinders mod folder.

**Comment by luciusmagn** [comment]
Oh cool, thanks for the info. Hopefully, the issue you are reporting will get resolved soon)
