### ISSUE TITLE
This archive is corrupt

### ISSUE THREAD

**Issue by Damaskox** [vawser/Cinders-DS3#38]
Trying to interact with the .zip file, WinRAR shoots out this error message.

Is the problem on my end?

![kuva](https://user-images.githubusercontent.com/76251763/118542613-e792da00-b75b-11eb-8710-82bbcc74b43f.png)

![kuva](https://user-images.githubusercontent.com/76251763/118542670-fed1c780-b75b-11eb-9b1f-96b83bf6235d.png)

I tried installing the .zip many times, but the same errors appear every time.

**Comment by Retr4y** [comment]
Same with me, F

**Comment by jerry-bn** [comment]
This repo exceeds the size limit of the standard zip format. You need to clone the repo.

**Comment by Damaskox** [comment]
Ok, I'll check it out.

ke 26. toukok. 2021 klo 22.06 Jerry ***@***.***) kirjoitti:
