### ISSUE TITLE
Consider posting mod releases on GitHub instead of nexusmods

### ISSUE THREAD

**Issue by Cypher121** [vawser/Cinders-DS3#6]
Since NexusMods now asks for money to have a reasonable download speed, it takes over half an hour to download cinders. Since it's already on github, hosting mod releases here seems like a good option.

**Comment by gwyndolin-chan** [comment]
I was just about to suggest this! It seems like it would be convenient :)

**Comment by luciusmagn** [comment]
Yea and it would be extremely easy, just tag a release in the clicky thing. No uploading or any much work required
