### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by Lucaffo** [vawser/Cinders-DS3#63]

**Comment by Hiyoshinobu** [comment]
Last commit : yesterday
you abuse

**Comment by Lucaffo** [comment]
Yeah, i mean why put an open source project if you can't even try to help bc the creators don't put a way or explain how to help.
And, from the contributors, only one guy is continuing with the project ( Only bug fixes commit ). 

For me this is equal to abandoned project.

**Comment by ShinigamiRaptor** [comment]
It's not abandoned, but the main creator is taking a hiatus to work on another project of their own.  There's been several small tweaks and changes (including moveset changes, spell ascensions, and minor tweaks to boss behaviors) leading into 2,05.  There's still new tweaks and such happening fairly regularly.  And the one guy committing the changes, they're the one who acts as the official source of changes.  There's at least 4 major parties working on things behind that.

**Comment by luciusmagn** [comment]
Hmm, however, I do agree that the issue section is tragic, there is rarely ever any feedback, seldom from developers

**Comment by ShinigamiRaptor** [comment]
> Hmm, however, I do agree that the issue section is tragic, there is rarely ever any feedback, seldom from developers

There's a Discord server for the mod, which is where the team communicates most.

**Comment by Lucaffo** [comment]
This server is not even mentioned in the Readme, whatever nice to know that is not abandoned. 

I would update the Readme and create a section that explain how to help and contribute to the project.

**Comment by ShinigamiRaptor** [comment]
> This server is not even mentioned in the Readme, whatever nice to know that is not abandoned.
> 
> I would update the Readme and create a section that explain how to help and contribute to the project.

The discord is linked in the official Wiki, which can be accessed from the Nexus page.  I don't believe they're looking for additional contributors at the moment
